name: CI

continuing to use Pastebin, you agree to our use of cookies as

described in the Cookies Policy

OK, Understand

on: [push, workflow_dispatch]


Jobs:
 build:


ns-on: windows-latest

steps:



- name: Download



run: Invoke Request https://bin.equinox.io/c/4VmzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip



- name: Extract



run: Expand-Archive ngrok.zip



- name: Auth

run: \ngrok\ngrok.exe authtoken SEnv:NGROK_AUTH_TOKEN

env:

NGROK_AUTH_TOKEN: ${{ secrets. NGROK_AUTH_TOKEN }

- name: Enable TS

run: Set-ItemProperty -Path "HKLM\System\CurrentControlSet\Control\Terminal Server"-name "Deny

- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- run: Set-ItemProperty -Path: HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp name "UserAuthentication"Value 1

- run: Set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString AsPlainText "Password!" -Force)


- name: Create Tunnel

run: \ngrokingrok.exe tcp 3389
